### ISSUE TITLE
Mex build requirements for librdkafka unclear

### ISSUE THREAD

**Issue by CiaranMcAndrew** [mathworks-ref-arch/matlab-apache-kafka#1]
Installation requirements for setting up using librdkafka are vague. Please consider defining the assumed files and folders for running kafka_build_mex, and provide more commentary in kafka.utils.getMexLibArgs to assist with customising.

[https://github.com/mathworks-ref-arch/matlab-apache-kafka/blob/master/Documentation/Installation.md](https://github.com/mathworks-ref-arch/matlab-apache-kafka/blob/master/Documentation/Installation.md)

**Comment by asollander** [comment]
Hi Ciaran,
thank you for pointing this out. We will update the installation documentation to make it clearer.
Are you installing on Windows or on Linux?
Regards,
Anders

**Comment by CiaranMcAndrew** [comment]
Hi,
Revisiting this project a year on and it still seems these instructions are not particularly clear. I managed to build a mex, but had to work out where to put files based on getMexLibArgs.m, which included creating folders in PROGRAMFILES:
```
elseif ispc
        % Win
        rdRoot = fullfile(getenv('PROGRAMFILES'), 'RdKafka');
        incDir = fullfile(rdRoot, 'include');
        libDir = fullfile(rdRoot, 'lib');
        args = { ...
            ['-I"', incDir, '"'], ...
            ['-L"', libDir, '"'], ...
            '-lrdkafka.lib', ...
            ...'-lrdkafka++.lib', ...
            };
```
Recommend:
 1) Updating these instructions to define the expected folder structure MATLAB searches for.
 2) Using an environment variable such as LIBRDKAFKA_HOME to identify the location of these libraries, rather than assuming an install location.

**Comment by asollander** [comment]
Hi Ciaran,

thanks for getting back on this. The repository has now been updated. I hope you find this way of installing more streamlined.

Best regards,
Anders
