### ISSUE TITLE
Create Kafka Consumer for MATLAB

### ISSUE THREAD

**Issue by kevin-lorenz** [mathworks-ref-arch/matlab-apache-kafka#2]
Kafka Producer has been developed for both MATLAB and Simulink, while Kafka Consumer is only available for Simulink.  Having a Consumer available in MATLAB would be very beneficial.

**Comment by asollander** [comment]
Hi Kevin,

we're currently investigating this option, and I will get back with an update soon.

Best regards,
Anders

**Comment by asollander** [comment]
Hello Kevin,

The latest release, 0.3.0, now contains a consumer for Kafka in MATLAB too.

If you need any support with this, feel free to reach out to me at mwlab@mathworks.com.

Best regards,
Anders

**Comment by kevin-lorenz** [comment]
It appears the `kafka_build_mex.m` script does not compile `mx_kafka_consumer.cpp`.
