### ISSUE TITLE
Broker hostname resolution

### ISSUE THREAD

**Issue by wardgssens** [mathworks-ref-arch/matlab-apache-kafka#5]
The log file shows the following error:
```
[2021-04-15 12:31:46](MW_INFO){KafkaConsumer} Just started consumer
[2021-04-15 12:31:46](MW_INFO){Broker(s)} localhost:9092
[2021-04-15 12:31:46](MW_INFO){Topic} vehicle
[2021-04-15 12:31:46](MW_INFO){Group} estimator
[2021-04-15 12:31:48](MW_INFO){KafkaLogger} RDKAFKA-3-FAIL: rdkafka#consumer-4: [thrd:GroupCoordinator]: GroupCoordinator: Failed to resolve '8c273868361d:9092': No such host is known.  (after 2300ms in state CONNECT)
```
I am trying to connect to a local Kafka cluster with `C = kafka.Consumer('localhost:9092', 'vehicle', 'estimator');`. As can be seen in the log file, the Matlab interface gets the broker hostname right, but somewhere in librdkafka it changes to `8c273868361d`. 

I can hotfix this issue by pointing `8c273868361d` to my local machine in my hosts file. This random value seems to be constant over multiple runs, even when I restart Matlab. It only changes when I restart my machine.

I built the librdkafka using vcpkg and made sure that the package contents are in `C:\Program files\RdKafka`. I copied `rdkafka.dll` to the Matlab build folder.

**Comment by asollander** [comment]
Hi Ward,
seeing you closed the issue, I assume you solved it. Would you care to share what the issue was? It could be helpful to add it to documentation if it happens to other people.

Thanks,
Anders

**Comment by wardgssens** [comment]
Hi,

I was a little too quick assuming the problem was in the library. I tried another approach using Python and got the same issue. The python library gave me much more information which allowed me to find the problem.

My Kafka broker was running inside a docker container and my advertised listeners were not set correctly. The “random” value was the hostname of the broker inside the docket network.

I solved this by configuring my Kafka broker as explained on this website https://www.kimsereylam.com/kafka/docker/2020/10/16/setup-local-kafka-with-docker.html

Thanks for replying!
Ward Goossens
________________________________
