### ISSUE TITLE
`C.consume(timeoutMillis)`  report error "Too many input arguments"

### ISSUE THREAD

**Issue by wyd888** [mathworks-ref-arch/matlab-apache-kafka#6]
Hi, when I attempted to run
```
[key, val, errMsg] = C.consume(timeoutMillis)
```

 I got the below error

<img width="305" alt="image" src="https://user-images.githubusercontent.com/7523578/154433774-57d2bc8c-951a-49f7-81cb-236c8e082fdf.png">

So the argument `timeoutMillis` is not actually implemented?

Thanks.

**Comment by asollander** [comment]
Hi,

thanks for commenting on this. I had to look into it, and it seems the documentation and the sources diverge in this case. My mistake, apologies.

I will try to address this soon.

Best regards,
Anders

**Comment by asollander** [comment]
This feature has now been added, in release 0.3.5.
