### ISSUE TITLE
convert int8 array to json

### ISSUE THREAD

**Issue by Bhee** [mathworks-ref-arch/matlab-apache-kafka#9]
Hi,
  I  am stuck in converting int8 array to json data in Matlab
Kafka is publishing data in JSON format. While using kafka.consume(), it returns values in int8 array.
How to convert int8 array to JSON format?

**Comment by asollander** [comment]
Hi,
provided I understand you correctly, you've read a bytes array from Kafka, containing int8 entries. Let's say you saved this into `bytes`. The following should do the trick.

```matlab
jsonStr = char(bytes);
value = jsondecode(jsonStr);
```

Hope this helps,
Anders

**Comment by Bhee** [comment]
Ok. Thank you
